name: DotnetTests

on:
    push:
        branches:
            - main
            - feature/*
    pull_request:
        branches:
            - main
            - feature/*

    workflow_dispatch:

jobs:
    tests:
        name: Tests
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
      
            - name: Set up .NET Core
              uses: actions/setup-dotnet@v1
              with:
                 dotnet-version: 7.0.x

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with: 
                node-version: 18
            - name: Install frontend dependencies
              run: cd BoxFactory-frontend && npm install

            - name: Build frontend
              run: cd BoxFactory-frontend && npm run build


            - name: Build Backend
              run: dotnet build BoxFactory/BoxFactoryAPI/BoxFactoryAPI.csproj
            
            - name: Run Backend
              run: dotnet run --project BoxFactory/BoxFactoryAPI/BoxFactoryAPI.csproj &
            
            - name: Sleep and kill
              run: sleep 15 && pkill -f "dotnet BoxFactoryAPI.dll" ||true
      
            - name: Run tests
              run: dotnet test BoxFactory/BoxFactoryUnitTests/BoxFactoryUnitTests.csproj