name: DotnetTests

on:
    push:
        branches:
            - main
            - feature/*
    pull_request:
        branches:
            - main
            - feature/*

    workflow_dispatch:

jobs:
    tests:
        name: Tests
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
      
            - name: Set up .NET Core
              uses: actions/setup-dotnet@v1
              with:
                 dotnet-version: 7.0.x

            - name: Build Backend
              run: dotnet build BoxFactory/BoxFactoryAPI/BoxFactoryAPI.csproj
            
            - name: Run Backend
              run: dotnet run BoxFactory/BoxFactoryAPI/BoxFactoryAPI.csproj & echo "API_PID=$!" >> $GITHUB_ENV
              env:
                 pgconn: ${{secrets.PGCONN}}
            
            - name: Sleep and kill
              run: sleep 15 && kill $API_PID
      
            - name: Run tests
              run: dotnet test BoxFactory/BoxFactoryUnitTests/BoxFactoryUnitTests.csproj